let deferredPrompt=null;let ticketsCache=[];
function escapeHtml(v){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")}
function formatDateTime(v){if(!v)return "—";const d=new Date(v);if(Number.isNaN(d.getTime()))return v;return d.toLocaleString("pt-BR")}
function priorityClass(p){return {"Baixa":"priority-baixa","Média":"priority-media","Alta":"priority-alta","Crítica":"priority-critica"}[p]||"priority-baixa"}
async function uploadFoto(file){if(!file)return null;const ext=(file.name.split(".").pop()||"jpg").toLowerCase();const fileName="foto_"+Date.now()+"."+ext;const {error}=await window.supabaseClient.storage.from("chamados-fotos").upload(fileName,file,{cacheControl:"3600",upsert:false,contentType:file.type||"image/jpeg"});if(error)throw error;const {data}=window.supabaseClient.storage.from("chamados-fotos").getPublicUrl(fileName);return data.publicUrl}
async function salvarChamado(event){event.preventDefault();const btn=event.target.querySelector("button[type='submit']");btn.disabled=true;btn.textContent="Salvando...";try{const file=document.getElementById("foto").files[0];const fotoUrl=await uploadFoto(file);const chamado={id:"CH-"+Date.now(),nome:document.getElementById("nome").value.trim(),unidade:document.getElementById("unidade").value,setor:document.getElementById("setor").value,setor_problema:document.getElementById("setorProblema").value.trim(),tipo_manutencao:document.getElementById("tipoManutencao").value,gravidade:document.getElementById("gravidade").value,descricao:document.getElementById("descricao").value.trim(),foto_url:fotoUrl,status:"Aberto",data_criacao:new Date().toISOString()};const {error}=await window.supabaseClient.from("chamados").insert([chamado]);if(error)throw error;alert("Chamado salvo com sucesso.");document.getElementById("ticketForm").reset();await carregarChamados()}catch(error){alert("Erro ao salvar chamado: "+error.message)}finally{btn.disabled=false;btn.textContent="Salvar chamado"}}
function getFilteredTickets(){const busca=document.getElementById("busca")?.value.toLowerCase().trim()||"";return ticketsCache.filter(ticket=>{const target=[ticket.id,ticket.nome,ticket.unidade,ticket.setor,ticket.setor_problema,ticket.descricao].join(" ").toLowerCase();return !busca||target.includes(busca)})}
function renderTicketList(){const list=document.getElementById("ticketList");const filtered=getFilteredTickets();if(!filtered.length){list.innerHTML='<div class="empty-state">Nenhum chamado encontrado.</div>';return}list.innerHTML=filtered.map(ticket=>`<article class="ticket-card"><div><h3>${escapeHtml(ticket.unidade)} • ${escapeHtml(ticket.setor)}</h3><div class="ticket-meta"><span class="badge badge-soft">${escapeHtml(ticket.id)}</span><span class="badge badge-soft">${escapeHtml(ticket.nome||"Sem nome")}</span><span class="badge badge-soft">${escapeHtml(ticket.tipo_manutencao||"—")}</span><span class="badge status-aberto">${escapeHtml(ticket.status||"Aberto")}</span><span class="badge ${priorityClass(ticket.gravidade)}">${escapeHtml(ticket.gravidade||"Baixa")}</span></div><p class="ticket-desc">${escapeHtml(ticket.descricao||"")}</p></div><div class="ticket-side"><div class="date-box"><strong>Criação:</strong><br>${formatDateTime(ticket.data_criacao)}</div>${ticket.foto_url?`<img class="thumb" src="${escapeHtml(ticket.foto_url)}" alt="Foto do chamado">`:""}</div></article>`).join("")}
async function carregarChamados(){const {data,error}=await window.supabaseClient.from("chamados").select("*").order("data_criacao",{ascending:false});if(error){alert("Erro ao carregar chamados: "+error.message);return}ticketsCache=Array.isArray(data)?data:[];renderTicketList()}
function registerPWA(){if("serviceWorker"in navigator){window.addEventListener("load",async()=>{try{await navigator.serviceWorker.register("./service-worker.js")}catch(error){console.error("Erro ao registrar Service Worker:",error)}})}window.addEventListener("beforeinstallprompt",(event)=>{event.preventDefault();deferredPrompt=event;document.getElementById("installButton").classList.remove("hidden")});const installButton=document.getElementById("installButton");installButton.addEventListener("click",async()=>{if(!deferredPrompt){alert("O navegador ainda não liberou a instalação.");return}deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;installButton.classList.add("hidden")});window.addEventListener("appinstalled",()=>{installButton.classList.add("hidden")})}
document.addEventListener("DOMContentLoaded",()=>{if(!window.supabaseClient){alert("Supabase não foi inicializado. Verifique o arquivo supabase.js.");return}registerPWA();document.getElementById("ticketForm").addEventListener("submit",salvarChamado);document.getElementById("busca").addEventListener("input",renderTicketList);carregarChamados()})
